version: "3.8"
services:
  betserver:
   build: ./
   container_name: betserver-c1
   ports: 
     - '9090:8080'   
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8080"
    volumes:
      - /c/Users/liako/git/bountyBetServer/betCoreServer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - betserver
   